[package]
name = "plain-text-health"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "pth"
path = "src/main.rs"

[dependencies]
chrono = "0.4.45"
clap = { version = "4.6.5", features = ["derive", "env"] }
datafusion = "55.1.0"
env_logger = "0.11.11"
log = "0.4.33"
logos = "0.16.1"
tokio = "1.53.1"
